// Database Schema for einfach verwaltet.
// v2: Added landlords, onboarding_sessions, ai_actions, conversations, documents, financial_transactions
// Using Neon PostgreSQL + Drizzle ORM

import { pgTable, text, timestamp, integer, boolean, decimal, uuid, jsonb } from 'drizzle-orm/pg-core';

// ─── EXISTING TABLES ────────────────────────────────────────────────────────

export const leads = pgTable('leads', {
  id: uuid('id').defaultRandom().primaryKey(),
  createdAt: timestamp('created_at').defaultNow(),
  verwaltungstyp: text('verwaltungstyp'),
  einheiten: text('einheiten'),
  standort: text('standort'),
  situation: text('situation'),
  prioritaet: text('prioritaet'),
  name: text('name').notNull(),
  email: text('email').notNull(),
  telefon: text('telefon'),
  status: text('status').default('new'),
  notes: text('notes'),
});

export const properties = pgTable('properties', {
  id: uuid('id').defaultRandom().primaryKey(),
  createdAt: timestamp('created_at').defaultNow(),
  landlordId: uuid('landlord_id'), // FK to landlords
  address: text('address').notNull(),
  postalCode: text('postal_code').notNull(),
  city: text('city').notNull().default('Hamburg'),
  unitCount: integer('unit_count').notNull(),
  verwaltungstyp: text('verwaltungstyp').notNull(), // miet | weg | sev
  ownerName: text('owner_name'),
  ownerEmail: text('owner_email'),
  ownerPhone: text('owner_phone'),
  active: boolean('active').default(true),
});

export const units = pgTable('units', {
  id: uuid('id').defaultRandom().primaryKey(),
  propertyId: uuid('property_id').notNull(),
  designation: text('designation').notNull(),
  areaM2: decimal('area_m2', { precision: 8, scale: 2 }),
  floor: integer('floor'),
  rooms: decimal('rooms', { precision: 4, scale: 1 }),
  coldRentCents: integer('cold_rent_cents'),
  occupied: boolean('occupied').default(true),
});

export const tenants = pgTable('tenants', {
  id: uuid('id').defaultRandom().primaryKey(),
  unitId: uuid('unit_id').notNull(),
  firstName: text('first_name').notNull(),
  lastName: text('last_name').notNull(),
  email: text('email'),
  phone: text('phone'),
  moveInDate: timestamp('move_in_date'),
  moveOutDate: timestamp('move_out_date'),
  active: boolean('active').default(true),
});

export const tickets = pgTable('tickets', {
  id: uuid('id').defaultRandom().primaryKey(),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  propertyId: uuid('property_id').notNull(),
  unitId: uuid('unit_id'),
  tenantId: uuid('tenant_id'),
  landlordId: uuid('landlord_id'), // FK to landlords
  title: text('title').notNull(),
  description: text('description'),
  category: text('category'), // maintenance | billing | complaint | other
  status: text('status').default('open'), // open | inprogress | resolved | closed
  priority: text('priority').default('normal'), // low | normal | high | urgent
  urgency: integer('urgency').default(2), // 1-5
  assignee: text('assignee'),
  aiTriage: jsonb('ai_triage'), // { category, urgency, summary }
  slaDeadline: timestamp('sla_deadline'),
  resolvedAt: timestamp('resolved_at'),
  rating: integer('rating'), // 1-5 stars, set by tenant after resolution
});

// ─── NEW TABLES v2 ───────────────────────────────────────────────────────────

// Landlords — property owners using einfach verwaltet.
export const landlords = pgTable('landlords', {
  id: uuid('id').defaultRandom().primaryKey(),
  email: text('email').notNull().unique(),
  name: text('name'),
  phone: text('phone'),
  companyName: text('company_name'),
  type: text('type').notNull().default('private'), // private | professional
  communicationChannel: text('communication_channel').default('email'), // email | whatsapp | portal
  aiAutonomyLevel: text('ai_autonomy_level').default('supervised'), // supervised | semi-auto | full-auto
  onboardingCompleted: boolean('onboarding_completed').default(false),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

// Onboarding sessions — save & resume progress
export const onboardingSessions = pgTable('onboarding_sessions', {
  id: uuid('id').defaultRandom().primaryKey(),
  landlordId: uuid('landlord_id').notNull(),
  currentStep: integer('current_step').default(1),
  totalSteps: integer('total_steps').default(7),
  type: text('type'), // private | professional
  data: jsonb('data').default({}), // accumulated form data
  completedAt: timestamp('completed_at'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

// AI Actions — action items generated by AI for landlord review
export const aiActions = pgTable('ai_actions', {
  id: uuid('id').defaultRandom().primaryKey(),
  landlordId: uuid('landlord_id').notNull(),
  propertyId: uuid('property_id'),
  unitId: uuid('unit_id'),
  tenantId: uuid('tenant_id'),
  type: text('type').notNull(), // mieterhoehung | mahnung | energieausweis | ticket | onboarding | custom
  urgency: integer('urgency').default(2), // 1-5
  title: text('title').notNull(),
  body: text('body'),
  actionLabel: text('action_label').default('Handeln'),
  dismissLabel: text('dismiss_label').default('Ignorieren'),
  status: text('status').default('pending'), // pending | actioned | dismissed
  metadata: jsonb('metadata').default({}),
  expiresAt: timestamp('expires_at'),
  createdAt: timestamp('created_at').defaultNow(),
});

// Conversations — all messages between tenants and verwaltung
export const conversations = pgTable('conversations', {
  id: uuid('id').defaultRandom().primaryKey(),
  tenantId: uuid('tenant_id'),
  landlordId: uuid('landlord_id').notNull(),
  ticketId: uuid('ticket_id'),
  channel: text('channel').default('portal'), // portal | email | whatsapp | sms
  direction: text('direction').notNull(), // inbound | outbound
  body: text('body').notNull(),
  aiGenerated: boolean('ai_generated').default(false),
  aiClassification: text('ai_classification'), // maintenance | payment | complaint | general
  aiUrgency: integer('ai_urgency'), // 1-5
  readAt: timestamp('read_at'),
  createdAt: timestamp('created_at').defaultNow(),
});

// Documents — document vault
export const documents = pgTable('documents', {
  id: uuid('id').defaultRandom().primaryKey(),
  landlordId: uuid('landlord_id').notNull(),
  propertyId: uuid('property_id'),
  unitId: uuid('unit_id'),
  tenantId: uuid('tenant_id'),
  type: text('type').notNull(), // mietvertrag | energieausweis | protokoll | abrechnung | sonstiges
  name: text('name').notNull(),
  url: text('url').notNull(), // Vercel Blob URL
  mimeType: text('mime_type'),
  sizeBytes: integer('size_bytes'),
  expiresAt: timestamp('expires_at'),
  metadata: jsonb('metadata').default({}),
  createdAt: timestamp('created_at').defaultNow(),
});

// Financial transactions — rent, expenses, Mahnungen
export const financialTransactions = pgTable('financial_transactions', {
  id: uuid('id').defaultRandom().primaryKey(),
  landlordId: uuid('landlord_id').notNull(),
  propertyId: uuid('property_id'),
  unitId: uuid('unit_id'),
  tenantId: uuid('tenant_id'),
  type: text('type').notNull(), // rent_received | expense | deposit | refund | mahnung
  amountCents: integer('amount_cents').notNull(), // €1 = 100 cents
  currency: text('currency').default('EUR'),
  status: text('status').default('pending'), // pending | confirmed | failed
  bkvCategory: text('bkv_category'), // §2 BetrKV category for BKA
  description: text('description'),
  dueDate: timestamp('due_date'),
  paidAt: timestamp('paid_at'),
  metadata: jsonb('metadata').default({}),
  createdAt: timestamp('created_at').defaultNow(),
});

// ─── BILLING TABLES v3 ───────────────────────────────────────────────────────

// Billing subscriptions — Stripe subscription tracking per landlord
export const billingSubscriptions = pgTable('billing_subscriptions', {
  id: uuid('id').defaultRandom().primaryKey(),
  landlordId: uuid('landlord_id').notNull().unique(),
  stripeCustomerId: text('stripe_customer_id').notNull().unique(),
  stripeSubscriptionId: text('stripe_subscription_id').unique(),
  stripePriceId: text('stripe_price_id'), // which tier price object
  tier: text('tier').notNull().default('basic'), // basic | standard | professional
  unitCount: integer('unit_count').notNull().default(1),
  monthlyAmountCents: integer('monthly_amount_cents'), // €/month incl. VAT
  status: text('status').default('incomplete'), // incomplete | active | past_due | canceled | unpaid
  sepaMandate: boolean('sepa_mandate').default(false), // SEPA Direct Debit mandate collected
  currentPeriodStart: timestamp('current_period_start'),
  currentPeriodEnd: timestamp('current_period_end'),
  cancelAtPeriodEnd: boolean('cancel_at_period_end').default(false),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

// Billing invoices — Stripe invoice records for German Rechnungen (§14 UStG)
export const billingInvoices = pgTable('billing_invoices', {
  id: uuid('id').defaultRandom().primaryKey(),
  landlordId: uuid('landlord_id').notNull(),
  stripeInvoiceId: text('stripe_invoice_id').notNull().unique(),
  invoiceNumber: text('invoice_number'), // Stripe sequential Rechnungsnummer
  subscriptionId: uuid('subscription_id'), // FK to billing_subscriptions
  status: text('status').default('draft'), // draft | open | paid | uncollectible | void
  amountDueCents: integer('amount_due_cents'), // Bruttobetrag
  amountPaidCents: integer('amount_paid_cents'),
  vatRatePercent: integer('vat_rate_percent').default(19), // 19% MwSt.
  vatAmountCents: integer('vat_amount_cents'), // MwSt. Betrag
  subtotalCents: integer('subtotal_cents'), // Nettobetrag
  pdfUrl: text('pdf_url'), // Stripe hosted invoice PDF
  hostedInvoiceUrl: text('hosted_invoice_url'), // Stripe hosted invoice page
  periodStart: timestamp('period_start'), // Leistungszeitraum von
  periodEnd: timestamp('period_end'), // Leistungszeitraum bis
  paidAt: timestamp('paid_at'),
  metadata: jsonb('metadata').default({}),
  createdAt: timestamp('created_at').defaultNow(),
});

// Billing events — webhook event log for audit trail
export const billingEvents = pgTable('billing_events', {
  id: uuid('id').defaultRandom().primaryKey(),
  stripeEventId: text('stripe_event_id').notNull().unique(),
  eventType: text('event_type').notNull(), // invoice.payment_succeeded etc.
  landlordId: uuid('landlord_id'),
  processed: boolean('processed').default(false),
  payload: jsonb('payload').default({}),
  processedAt: timestamp('processed_at'),
  createdAt: timestamp('created_at').defaultNow(),
});
